from typing import Any, Generator
from sympy.core.function import UndefinedFunction
from sympy.utilities.decorator import deprecated

def n_order(a, n) -> int:
    ...

def primitive_root(p, smallest=...) -> int | None:
    ...

def is_primitive_root(a, p) -> bool:
    ...

def sqrt_mod(a, p, all_roots=...) -> list[int] | int | None:
    ...

def sqrt_mod_iter(a, p, domain=...) -> Generator[int, Any, None]:
    ...

def is_quad_residue(a, p) -> bool:
    ...

def is_nthpow_residue(a, n, m) -> bool:
    ...

def nthroot_mod(a, n, p, all_roots=...) -> list[int] | int | list[Any] | None:
    ...

def quadratic_residues(p) -> list[int]:
    ...

def legendre_symbol(a, p) -> type[UndefinedFunction]:
    ...

def jacobi_symbol(m, n) -> type[UndefinedFunction]:
    ...

def mobius(n) -> type[UndefinedFunction]:
    ...

def discrete_log(n, a, b, order=..., prime_order=...) -> int:
    ...

def quadratic_congruence(a, b, c, n) -> list[int] | list[Any]:
    ...

def polynomial_congruence(expr, m) -> list[int] | int | list[Any] | None:
    ...

def binomial_mod(n, m, k) -> int:
    ...

