from functools import lru_cache
from typing import Any, Literal

def num_digits(n, base=...) -> int | Any:
    ...

def integer_log(n, b) -> tuple[Any, Any] | tuple[Literal[0], Literal[False]] | tuple[Any, Literal[False]] | tuple[Literal[0], bool] | tuple[int, Any | bool]:
    ...

def trailing(n) -> Literal[0] | None:
    ...

@lru_cache(1024)
def igcd(*args) -> int:
    ...

igcd2 = ...
def igcd_lehmer(a, b) -> int:
    ...

def ilcm(*args) -> int:
    ...

def igcdex(a, b) -> tuple[Literal[0], Literal[1], Literal[0]] | tuple[Any | int, Any | int, Any | Literal[0]]:
    ...

def mod_inverse(a, m) -> int:
    ...

def isqrt(n) -> int:
    ...

def integer_nthroot(y, n) -> tuple[int, Any | bool]:
    ...

