from types import NotImplementedType
from typing import Any, Self
from sympy.polys.matrices.ddm import DDM
from sympy.polys.matrices.dfm import DFM_dummy
from sympy.utilities.decorator import doctest_depends_on

class SDM(dict):
    fmt = ...
    is_DFM = ...
    is_DDM = ...
    def __init__(self, elemsdict, shape, domain) -> None:
        ...
    
    def getitem(self, i, j):
        ...
    
    def setitem(self, i, j, value) -> None:
        ...
    
    def extract_slice(self, slice1, slice2) -> Self:
        ...
    
    def extract(self, rows, cols) -> Self:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self) -> str:
        ...
    
    @classmethod
    def new(cls, sdm, shape, domain) -> Self:
        ...
    
    def copy(A) -> Self:
        ...
    
    @classmethod
    def from_list(cls, ddm, shape, domain) -> Self:
        ...
    
    @classmethod
    def from_ddm(cls, ddm) -> Self:
        ...
    
    def to_list(M) -> list[Any]:
        ...
    
    def to_list_flat(M):
        ...
    
    @classmethod
    def from_list_flat(cls, elements, shape, domain) -> Self:
        ...
    
    def to_flat_nz(M) -> tuple[list[Any], tuple[tuple[tuple[Any, Any], ...], Any]]:
        ...
    
    @classmethod
    def from_flat_nz(cls, elements, data, domain) -> Self:
        ...
    
    def to_dod(M) -> dict[Any, Any]:
        ...
    
    @classmethod
    def from_dod(cls, dod, shape, domain) -> Self:
        ...
    
    def to_dok(M) -> dict[tuple[Any, Any], Any]:
        ...
    
    @classmethod
    def from_dok(cls, dok, shape, domain) -> Self:
        ...
    
    def to_ddm(M) -> DDM:
        ...
    
    def to_sdm(M) -> Self:
        ...
    
    @doctest_depends_on(ground_types=['flint'])
    def to_dfm(M) -> DFM_dummy:
        ...
    
    @doctest_depends_on(ground_types=['flint'])
    def to_dfm_or_ddm(M) -> DFM_dummy | DDM:
        ...
    
    @classmethod
    def zeros(cls, shape, domain) -> Self:
        ...
    
    @classmethod
    def ones(cls, shape, domain) -> Self:
        ...
    
    @classmethod
    def eye(cls, shape, domain) -> Self:
        ...
    
    @classmethod
    def diag(cls, diagonal, domain, shape=...) -> Self:
        ...
    
    def transpose(M) -> Self:
        ...
    
    def __add__(A, B) -> NotImplementedType | Self:
        ...
    
    def __sub__(A, B) -> NotImplementedType | Self:
        ...
    
    def __neg__(A) -> Self:
        ...
    
    def __mul__(A, B) -> Self | NotImplementedType:
        ...
    
    def __rmul__(a, b) -> Self | NotImplementedType:
        ...
    
    def matmul(A, B) -> Self:
        ...
    
    def mul(A, b) -> Self:
        ...
    
    def rmul(A, b) -> Self:
        ...
    
    def mul_elementwise(A, B) -> Self:
        ...
    
    def add(A, B) -> Self:
        ...
    
    def sub(A, B) -> Self:
        ...
    
    def neg(A) -> Self:
        ...
    
    def convert_to(A, K) -> Self:
        ...
    
    def nnz(A) -> int:
        ...
    
    def scc(A) -> list[Any]:
        ...
    
    def rref(A) -> tuple[Self, list[Any]]:
        ...
    
    def rref_den(A) -> tuple[Self, Any, Any]:
        ...
    
    def inv(A) -> SDM:
        ...
    
    def det(A):
        ...
    
    def lu(A) -> tuple[Self, Self, list[Any]]:
        ...
    
    def lu_solve(A, b) -> Self:
        ...
    
    def nullspace(A) -> tuple[Self, list[int]]:
        ...
    
    def nullspace_from_rref(A, pivots=...) -> tuple[Self, list[int]] | tuple[Self, list[Any]]:
        ...
    
    def particular(A) -> Self:
        ...
    
    def hstack(A, *B) -> Self:
        ...
    
    def vstack(A, *B) -> Self:
        ...
    
    def applyfunc(self, func, domain) -> Self:
        ...
    
    def charpoly(A):
        ...
    
    def is_zero_matrix(self) -> bool:
        ...
    
    def is_upper(self) -> bool:
        ...
    
    def is_lower(self) -> bool:
        ...
    
    def is_diagonal(self) -> bool:
        ...
    
    def diagonal(self) -> list[Any]:
        ...
    
    def lll(A, delta=...):
        ...
    
    def lll_transform(A, delta=...) -> tuple[Any, Any]:
        ...
    


def binop_dict(A, B, fab, fa, fb) -> dict[Any, Any]:
    ...

def unop_dict(A, f) -> dict[Any, Any]:
    ...

def sdm_transpose(M) -> dict[Any, Any]:
    ...

def sdm_dotvec(A, B, K):
    ...

def sdm_matvecmul(A, B, K) -> dict[Any, Any]:
    ...

def sdm_matmul(A, B, K, m, o) -> dict[Any, Any]:
    ...

def sdm_matmul_exraw(A, B, K, m, o) -> dict[Any, Any]:
    ...

def sdm_irref(A) -> tuple[dict[int, Any], list[Any], dict[Any, set[int]]]:
    ...

def sdm_rref_den(A, K):
    ...

def sdm_nullspace_from_rref(A, one, ncols, pivots, nonzero_cols) -> tuple[list[Any], list[int]]:
    ...

def sdm_particular_from_rref(A, ncols, pivots) -> dict[Any, Any]:
    ...

def sdm_berk(M, n, K) -> dict[int, Any] | dict[Any, Any]:
    ...

