from typing import Any


def lra_satask(proposition, assumptions=..., context=...) -> bool | None:
    ...

WHITE_LIST = ...
def check_satisfiability(prop, _prop, factbase) -> bool | None:
    ...

pred_to_pos_neg_zero = ...
def get_all_pred_and_expr_from_enc_cnf(enc_cnf) -> tuple[set[Any], set[Any]]:
    ...

def extract_pred_from_old_assum(all_exprs) -> list[Any]:
    ...

